### ISSUE TITLE
Weird failure to run

### ISSUE THREAD

**Issue by vdavez** [vdavez/scotus-servo#1]
Half the time, when I run `node app.js`, the script doesn't actually run anything. (It also doesn't give an error). It just goes straight to the end and says "All done". But if I send a `curl` request to the site and try again, it works beautifully. I have _no_ idea why this might be. My guess is that it has something to do with the `request` module, but..

**Comment by konklone** [comment]
Wow, I can reproduce this perfectly. I have no idea what is happening. I think the next steps would to be to open a `node` shell from the project dir the next time it's happening, and see if you can repeatedly reproduce it with straight `request` calls. And if you can, to then try to repeatedly reproduce it with core Node [`http` library](http://nodejs.org/api/http.html) calls.

**Comment by vdavez** [comment]
Ah. The plot thickens... when i use the core http library call, i discovered that it gets _this_ page sometimes: http://www.supremecourt.gov/errors/RequestError.aspx?aspxerrorpath=/opinions/slipopinions.aspx

That explains why it breaks; it's not `request`, it's the SCOTUS site. But _why_?, I wonder. Perhaps there's a user-agent thing?

**Comment by konklone** [comment]
Try setting a custom user agent in `requests`. You could do one with the name/URL of this project, or you could mimic curl, if SCOTUS has specifically whitelisted that one. (It could even just be that SCOTUS needs to see _some_ user agent from an IP, and lets it through for a while.)

**Comment by vdavez** [comment]
Tried that last night and it didn't work (both Mozilla and curl). But I could have done it wrong...

**Comment by vdavez** [comment]
I fixed this a while ago, so closing it.
