### ISSUE TITLE
Suggestions for tweets about new opinions

### ISSUE THREAD

**Issue by konklone** [vdavez/scotus-servo#6]
Today's updates:

![scotus](https://cloud.githubusercontent.com/assets/4592/3288369/002e743e-f562-11e3-816f-11b38264fd8a.png)

They'd be much more click-through-able with the opinion's title in the tweet. It looks like the titles are available for easy scraping:

![titles](https://cloud.githubusercontent.com/assets/4592/3288402/4c746524-f562-11e3-8565-a9dc0b81fe63.png)

I also think "Download at" is unneeded, especially if space is at a higher premium. 

Finally, I think people will be more likely to click through when the link is at supremecourt.gov, rather than code.esq.io. For better or worse.

Suggested tweet text:

> The Supreme Court just ruled on "Abramski v. United States". http://www.supremecourt.gov/...

**Comment by vdavez** [comment]
Great suggestions! 
1. **Opinion titles.** My only concern in the opinion title is the 140 character limit... 
2. **Links.** The click-thru to SCOTUS is a very good recommendation. I'll keep the "old" opinion link at code.esq.io.

Thanks!

**Comment by vdavez** [comment]
But, i guess i could just do everything before the "v." if the opinion title is too long...

E.g.,

> Supreme Court just ruled on "Ray Haluch Gravel Co." http://www.supremecourt.gov/... 

but 

> Supreme Court just ruled on "Republic of Argentina v. NML Capital, Ltd." http://www.supremecourt.gov/...

**Comment by vdavez** [comment]
Just realized something about the links to SCOTUS. When they change an opinion, the previous link dies, so it would have the effect of breaking my earlier tweet. Is that a concern?

**Comment by vdavez** [comment]
FWIW, it looks like all i would need to do is get the inner text for the `a` element captured on this line: https://github.com/vzvenyach/scotus-servo/blob/gh-pages/app.js#L63, pass it (and the link) to the callback on this line: https://github.com/vzvenyach/scotus-servo/blob/gh-pages/app.js#L72, and then pass them on this line https://github.com/vzvenyach/scotus-servo/blob/gh-pages/app.js#L37 to the `gitTweet` function and rewrite this line: https://github.com/vzvenyach/scotus-servo/blob/gh-pages/app.js#L118

I note this for my own edification later.

**Comment by konklone** [comment]
For character limit, I would just enforce that you display up to X characters of the title, using a Unicode one-char ellipse (`…`) to handle overflow. (e.g. "Republic of Argentina v. NML Ca…").

Well, if you used the code.esq.io URL, wouldn't it change under your feet if they updated the opinion? You'd be linking to a different opinion than what you had originally done. Though you also have other backup permalinks for individual opinion versions?

A couple ideas of handling it:
- Include both links in the tweet. e.g. add `Backup: code.esq.io/...`. Cons: takes up more space, makes tweets denser. (Could be mitigated with newlines, which also take up more chars.) Pros: more direct, can forget about tweet once it's posted.
- If the opinion ever changes, have the update tweet be a reply to the tweet where it was originally posted. Cons: requires tracking tweet/opinion relationships. Pros: takes up no more chars or tweets than you'd otherwise do (informatically, all upside).

**Comment by vdavez** [comment]
Closed per 5a9ebde. Looking forward to seeing it in action in the morning.
